server:
  port: 8082

spring:
  application:
    name: speech-service
  main:
    lazy-initialization: true
    banner-mode: off
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: false
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: WARN
    com.example.speechservice: INFO

openai:
  api:
    api-key: ${OPENAI_API_KEY}


