server:
  port: 8083

spring:
  application:
    name: speech-service
  main:
    lazy-initialization: true
    banner-mode: off
  
  datasource:
    url: jdbc:mysql://localhost:3306/speechservice?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: speechuser
    password: speechpass
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: WARN
    com.example.speechservice: INFO

openai:
  api:
    api-key: ${OPENAI_API_KEY}

---
# Docker 프로파일 설정
spring:
  config:
    activate:
      on-profile: docker
  
  data:
    redis:
      host: redis
      port: 6379

logging:
  level:
    root: INFO
    com.example.speechservice: DEBUG

